### PR TITLE
Build the image_geometry library shared.

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

connects to ros2/ros2#342

CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/2682/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/229/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2142/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/2806/)

### CODE REVIEW

**Comment by wjwwood** [comment]
I think you should instead change this line:

https://github.com/ros2/vision_opencv/blob/ros2/image_geometry/package.xml#L20

To depend on https://github.com/ros2/ament_cmake_ros rather than just `ament_cmake`. That should default libraries to shared (which is in keeping with ROS 1 and more likely to "just work" for ported ROS 1 packages).

I can't find the original discussion of setting up this package for this purpose, but it was. Maybe @dirk-thomas can find the original conversation more easily.

**Comment by clalancette** [comment]
Hm, so if I do that change to depend on ament_cmake_ros in package.xml, and don't add SHARED into the CMakeLists.txt, I see this:

```
[ 11%] Building CXX object CMakeFiles/image_geometry.dir/src/pinhole_camera_model.cpp.o
[ 33%] Built target gtest
[ 44%] Building CXX object CMakeFiles/image_geometry.dir/src/stereo_camera_model.cpp.o
[ 66%] Built target gtest_main
[ 77%] Linking CXX static library libimage_geometry.a
```

Is that expected?

**Comment by wjwwood** [comment]
You need to `find_package` it too (again rather than just `ament_cmake`), sorry I should have mentioned that.

**Comment by mikaelarguedas** [comment]
I think this commit is a good example of how to use it https://github.com/ros2/rmw/commit/3e9de3c086e800908c8ee0870e977aeb8a761efe

**Comment by clalancette** [comment]
Ah, perfect.  That did it.  Thanks, I'll update this PR with that.

**Review by wjwwood — APPROVED** [review]

**Comment by mikaelarguedas** [comment]
looks like this failed to link on windows: `fatal error LNK1181`

**Comment by clalancette** [comment]
Yeah, Windows is being difficult here.  Not sure why yet, will look into it.

**Comment by clalancette** [comment]
Thanks to help from @wjwwood , I think I've got it.  I'm re-running the full CI on Windows just to be sure.  A re-review would be helpful, just in case I missed anything relevant.

**Review by wjwwood — APPROVED** [review]

**Comment by clalancette** [comment]
Thanks!  CI passed, merging.

**Pull request merged**
